apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      initContainers:
        - name: copy-app
          image: ghcr.io/tinux-it/todo:latest
          command: [ "sh", "-c", "cp -r /app/. /app-shared" ]
          volumeMounts:
            - name: app-volume
              mountPath: /app-shared

      containers:
        - name: php-fpm
          image: ghcr.io/tinux-it/todo:latest
          volumeMounts:
            - name: app-volume
              mountPath: /app
            - name: php-socket
              mountPath: /php-socket
          envFrom:
            - secretRef:
                name: todo-app-secrets
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-volume
              mountPath: /app
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: php-socket
              mountPath: /php-socket
          envFrom:
            - secretRef:
                name: todo-app-secrets
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: php-socket
          emptyDir: {}
